- name: Configure the cron docker unused resources prune task
  hosts: all
  roles:
    - role: manala.cron
      manala_cron_files:
        - file: docker-prune
          user: root
          environment:
            - PATH: /usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
          jobs:
            - name: Prune docker resources
              job: "docker system prune -f --all"
              minute: 30
              hour: 4

