- name:  Install Docker on the swarm hosts
  hosts: swarm
  roles:
    - role: geerlingguy.docker
      docker_apt_ignore_key_error: False
      docker_service_state: started
      docker_install_compose: true

