- hosts: swarm
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Update nodejs package apt /modern version/
      shell: 'curl -sL https://deb.nodesource.com/setup_20.x | bash - '

    - name: Install nodejs
      apt:
        name: nodejs
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: file | Configure appropiate symbolic links for nodejs
      file:
        src: "{{ item.source }}"
        dest: "{{ item.dest }}"
        state: link
      loop:
        - { source: "/usr/bin/node", dest: "/etc/alternatives/nodejs" }
        - { source: "/etc/alternatives/nodejs", dest: "/usr/bin/nodejs" }

    - name: Install vim
      apt:
        name: vim
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes
        cache_valid_time: 3600

    #Changing to python3-pip 20230926
    - name: Install python3-pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Install docker
      pip:
        name: docker
        state: present
